### PR TITLE
Convert WP7 ChildBrowser to Cordova 1.5.0

### PR DESCRIPTION
**Pull request by kerrishotts**
The only changes I've made is to alter the namespace and usings in the .cs file and change PhoneGap to Cordova in the .js file. 

Ignore the other commits -- I'll learn to use git eventually!

I can't vouch for anything above v1.5 of Cordova; I suspect it would work fine, but am not yet able to test. When I move to 1.7 for WP7 (or a later version), I'll reverify.

### CODE REVIEW

**Comment by mtamony** [comment]
Have you been able to get CB working in WP7? I have it set up essentially like my Android app, which works fine, but can't get anything to happen in WP7.

**Comment by kerrishotts** [comment]
Yes, with this, anyway (with the .cs file added to the project under Plugins):

```
  var options = 
  {
     url:theURL,
     geolocationEnabled:false
  };
      Cordova.exec(null, null,"ChildBrowserCommand","showWebPage", options);
```

That /should/ get it going, assuming all the other setup is correct. (index page loading the childbrowser.js file and the .cs file in the right place.)

**Comment by mtamony** [comment]
I have it working now. I am now having some difficulty with navigating in WP7. I set up separate html files in my www folder. In one I want to get back to an .xaml file in the same folder. I can't seem to get it going.

**Comment by Viras-** [comment]
Merged.

As with the other plugin, would be nice to have a version for Cordova 1.6+!

**Pull request merged**
