### PR TITLE
moved iOS/iPhone EmailComposer plugins to outside repo

### PR DESCRIPTION
**Pull request by steve-jansen**
Moved 3 iOS/iPhone plugins into a single repo @ https://github.com/steve-jansen/cordova-ios-emailcomposer:
- iOS/EmailComposer
- iOS/EmailComposerWithAttachments
- iPhone/EmailComposer

New features / changes:
- plugman/cordova-cli support
- cordova plugin spec 2.x+ implement
- ARC support
- improved JS API
- unit tests
- and more, see see https://github.com/steve-jansen/cordova-ios-emailcomposer/README.md

### CODE REVIEW

**Comment by purplecabbage** [comment]
I wish I had written that in 2005, can you change the date of creation to April 5, 2010 please?
: Created by Jesse MacFadyen on 10-04-05

**Comment by steve-jansen** [comment]
Good catch.

Updated https://github.com/steve-jansen/cordova-ios-emailcomposer#credits

```
    diff --git a/README.md b/README.md
    index ce9091a..1ab4f75 100644
    --- a/README.md
    +++ b/README.md
    @@ -102,7 +102,7 @@ embedding both `EmailComposer.js` and `EmailComposer-Deprecated.js`

     ### Credits

    -  - Created by Jesse MacFadyen on October 2005
    +  - Created by Jesse MacFadyen on April 5th, 2010
       - Added Cordova 1.5 support by @RandyMcMillan on March 2012
```

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Comment by steve-jansen** [comment]
Hi, I did what you asked in http://shazronatadobe.wordpress.com/2012/11/07/cordova-plugins-put-them-in-your-own-repo-2/... then you leave my pull request open for 90 days without merging?  This was a README update with a pointer to the new maintenance repo…

**Comment by shazron** [comment]
Sorry about this :( but check out the new README with the link "Cordova Plugin Registry".

**Pull request closed without merging**
