### PR TITLE
Fixed Issue #400

### PR DESCRIPTION
**Pull request by leo-zhao**
Hi there,

I raised issue #400 tow days ago, and did more testing on my app with the file-uploader plugin.
Luckily found the problems, and got them fixed. Now it works on my app.

Regards

Leo Zhao

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
We should have put the updated Cordova plugin in /iOS so the /iPhone doesnt have mixed versions.

**Comment by leo-zhao** [comment]
That is a good idea, but we don't have fileuploader plugin in the IOS repository currently. Maybe you guys need make some kind of decision on which one should be in IOS or IPHONE.

**Comment by RandyMcMillan** [comment]
iphone is for PhoneGap 
iOS is for Cordova moving forward.

**Comment by RandyMcMillan** [comment]
I copied the Fileuploader plugin to iOS but please retest for me. After confirm I'm going to roll back the /iPhone version to PhoneGap. If we keep the /iphone and /iOS repos sterile then there will be a lot less confusion moving forward. I realized the potential problems that can arise when I added dual PhoneGap/Cordova support to ChildBrowser initially. I realized that there are actually some plugins that havnt even been updated to PhoneGap 1.4.1 and are basically orphans. By migrating the plugins to /iOS we are cleaning up the repo, creating a new base line for future support of Cordova and preserving "PhoneGap" plugins for established projects that will not be able to keep up with the release cadence of Cordova as it incubates in ASF.

**Comment by leo-zhao** [comment]
Now I see the different between iphone and ios repository.
Thanks for the clarify.
I will help to confirm fileuploader works under ios after hours tonight, and update you.

**Comment by leo-zhao** [comment]
Have tested file uploader under ios repository, and it works well on my app with file uploading and progress bar.
I guess you can roll back the iphone version to phonegap if you like.

**Comment by RandyMcMillan** [comment]
thanks

**Comment by leo-zhao** [comment]
No worries.

**Pull request merged**
