### PR TITLE
plugin updated to work with PhoneGap 1.0.0

### PR DESCRIPTION
**Pull request by DanielTizon**
Hi guys,

I have updated the plugin to work with PhoneGap 1.0.0, and I have tested it, everything is working fine.

### CODE REVIEW

**Comment by macdonst** [comment]
In 5b05210 you should just remove the .js and .jar files. People can supply their own.

**Comment by DanielTizon** [comment]
Hey macdonst, can you see my last changes? I havent worked too much with github, so I dont know if I need to do a new pull request or not.

**Comment by DanielTizon** [comment]
I have just removed "PhoneGap.addPlugin lines", but if I remove "window.plugins.bluetooth = new Bluetooth();", I get the next error on console:

D/PhoneGapLog( 1694): file:///android_asset/www/index.html: Line 48 : Uncaught TypeError: Cannot call method 'isBTEnabled' of undefined
E/Web Console( 1694): Uncaught TypeError: Cannot call method 'isBTEnabled' of undefined at file:///android_asset/www/index.html:48

and I have added a new function for unpair your mobile of any paired bluetooth device.

**Comment by macdonst** [comment]
You need to change your index.html so that it doesn't try to register for Bluetooth events until after you get a "deviceready" event. Once you get a deviceready you can be sure that PhoneGap and your plugins are loaded.

**Comment by DanielTizon** [comment]
I have removed " window.plugins.bluetooth = new Bluetooth();" of js, and I did some changes on index.html, but I still need use that line after "deviceready" (in index.html) or it doesnt work.

**Comment by macdonst** [comment]
You accidentally removed:

  PhoneGap.addConstructor(function() {
    PhoneGap.addPlugin('Bluetooth', new Bluetooth());
  });

from bluetooth.js.  If you put that back into the file you won't need to explicitly add the line to create the Bluetooth object in your index.html.

**Comment by DanielTizon** [comment]
According to this page: 

http://wiki.phonegap.com/w/page/36753494/How%20to%20Create%20a%20PhoneGap%20Plugin%20for%20Android

I needn't use "PhoneGap.addPlugin" in bluetooth.js, and I also have removed " window.plugins.bluetooth = new Bluetooth();" of index.html. I had to change the way I was using to call functions. Everything is working nice now.

**Comment by macdonst** [comment]
Personally, I think you should roll back to commit e23162b and add the 3 line PhoneGap.addConstrutor() code that I put in my last comment. It lines up better with the way the core PhoneGap code is written.

Thanks for bringing the wiki article to my attention. I'm off to re-write parts of it now.

**Comment by DanielTizon** [comment]
Ok, I added the constructor, and commited it, because in 0984e99 I also modified the index.html (dummy app with examples). So I hope everything will be nice now.

**Pull request merged**
