### PR TITLE
Sms plugin

### PR DESCRIPTION
**Pull request by dshookowsky**
This is a plugin that I'd like to commit to the PhoneGap project.  I've incorporated naming changes recommended by Simon Mac Donald and unit tested this on a pair of emulators

### CODE REVIEW

**Comment by macdonst** [comment]
Hey Dan, 

Generally we don't check in the entire project into the plugins directory. You'll want to create a src directory for your java code, a www directory for your .js file and a README.md explaining how to install and use your plugin. Plus you may want to put in your own LICENSE file, I recommend a MIT license. 

On another note you'll want to look into .gitignore files to see how to exclude files from GIT. For instance I generally ignore anything in the bin directory of my projects.

Simon

**Comment by dshookowsky** [comment]
I'll get it fixed.  Thanks for your patience.

**Comment by macdonst** [comment]
Np, meng. It's a learning experience for all of us.

**Comment by dshookowsky** [comment]
OK, at the risk of annoying you, do I have to close the previous pull
request and create a new one?  I'm a subversion guy, the git stuff is
still new to me.

On Wed, Oct 26, 2011 at 11:07 AM, macdonst
reply@reply.github.com
wrote:

**Comment by macdonst** [comment]
Hmm..I'm not sure if you can add a commit to an already open pull
request. Probably just as easy to close and open a new one.

Simon Mac Donald
http://hi.im/simonmacdonald

On Wed, Oct 26, 2011 at 12:21 PM, Daniel Shookowsky
reply@reply.github.com
wrote:

**Comment by dshookowsky** [comment]
Closing this to issue new pull request

**Pull request closed without merging**
