### PR TITLE
Contact Activity for Android

### PR DESCRIPTION
**Pull request by grandecomplex**
Hello,

I made a plugin for Android. I can send you a screencast if you'd like. Essentially when inside a PhoneGap webview, a user can tap an HTML element to open a native contact listview. When the user makes a selection, they are sent back to the PhoneGap webview with that contact showing in an HTML input field. It is a very fast and an efficient way to show and grab a contact.

Currently it only allows the user to get the name, but I need to make it so it grabs email and telephone also. This will come in future iterations.

Thanks!
Alex

### CODE REVIEW

**Comment by ascorbic** [comment]
Rather than directly changing the content of the elements from within the plugin callback, wouldn't it be better to let the user decide what to do with the result by allowing them to pass a callback to show()? It would give a bit more flexibility.

**Comment by grandecomplex** [comment]
Why didn't I think of this already! Fixing now...

**Comment by grandecomplex** [comment]
Fixed... Much better. I should have done that already.

**Comment by grandecomplex** [comment]
Whoops I hit "close" on the pull request...

**Pull request closed without merging**
