### PR TITLE
Improve NativeControls plugin, finally supporting the navigation bar and buttons

### PR DESCRIPTION
**Pull request by AndiDog**

### CODE REVIEW

**Comment by devgeeks** [comment]
This is a pretty massive change. 

Are you sure you wouldn't rather make a new plugin?

I have been thinking the NativeControls plugin would be better split off into smaller plugins. There is already a good ActionSheet plugin, and NativeControls was good as a TabBar plugin..

Maybe what we need to do is put NativeControls out of its misery and have plugins for each feature?

**Comment by AndiDog** [comment]
You're right, the change only affects the navigation bar. Just wanted to make it finally right because nobody updated it for a while. It also seems there's another plugin with the same name in the iPhone folder (seems to be a more dated version).

If you want, I can reset and instead move the new things into a "NavigationBar" plugin.

**Comment by devgeeks** [comment]
Would that be ok with you?

I will for my part try and split out a new tabbar only plugin as well and maybe we can deprecate the NativeControls plugin once and for all..

**Comment by AndiDog** [comment]
Sounds good. Then I will just reset my commit and split off a new plugin. Will report back with another pull request ;)

**Pull request closed without merging**
