### PR TITLE
Add Cordova support to GoogleAnalytics for iOS

### PR DESCRIPTION
**Pull request by ckihneman**
Followed the [Cordova Plugin Upgrade Guide](https://github.com/apache/incubator-cordova-ios/blob/master/guides/Cordova%20Plugin%20Upgrade%20Guide.md) to bring support for GoogleAnalytics to iOS for Cordova 1.5.0 or better.

All is working as expected.

### CODE REVIEW

**Comment by ckihneman** [comment]
#462 needs to be merged in to fix this commit, complies with 1.5.0 and 1.6.0 as per @shazron's [updated cordova plugin guide](http://git-wip-us.apache.org/repos/asf?p=incubator-cordova-ios.git;a=blob;f=guides/Cordova+Plugin+Upgrade+Guide.md;h=aee45d9137238b0b7f6160add915ee8f6a1f2b76;hb=9d5587e4b9cecf0b737b22b01d18e67a5a42db57)

https://github.com/phonegap/phonegap-plugins/pull/462

Thanks!

**Comment by thiagorobis** [comment]
Any chance to do the same to Android Plugin?

**Comment by ckihneman** [comment]
Sorry @thiagorobis, I'm no help on that one. Hopefully another kind soul will come along and do it up for you.

**Comment by thiagorobis** [comment]
Ok,
Thank you! I hope too! ;D

On Tue, Apr 17, 2012 at 15:05, Chris Kihneman <
reply@reply.github.com

**Comment by RandyMcMillan** [comment]
SO #462 is good?

**Comment by ckihneman** [comment]
Yes it is, thanks @RandyMcMillan!

**Pull request merged**
