### PR TITLE
[iOS] powermanager updated for latest cordova

### PR DESCRIPTION
**Pull request by ghost**
updated powermanager iOS plugin to work with latest cordova 2.1.0

Previous version didn't seem to work, now using cordova.addConstructor.

plus: clean trailing spaces, missing semicolons, idiomaticjs style, safer check on window.plugins

### CODE REVIEW

**Comment by ghost** [comment]
urgh, github editor keeps adding trailing spaces and off stuff, how the hell do I add a commit to a pull request heh

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904
https://github.com/phonegap/phonegap-plugins/issues/889

**Comment by devgeeks** [comment]
Bit too big a change to an important plugin.

@shazron  ?

**Comment by aeosynth** [comment]
could ios dimming support be added to this plugin? currently the screen stays at full brightness.

http://stackoverflow.com/questions/8234981/make-the-iphone-screen-dim

http://developer.apple.com/library/IOs/#documentation/UIKit/Reference/UIScreen_Class/Reference/UIScreen.html

edit: specify ios dimming

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Pull request closed without merging**
