### PR TITLE
Created a new iPhone/MessageBox plugin

### PR DESCRIPTION
**Pull request by mgcrea**
Unified api to display message boxes (alert/confirm/prompt).
Ability to prompt with message, placeholder & type (ie. password).

Tried to build a very clean&documented code.

### CODE REVIEW

**Comment by max-mapper** [comment]
Showing alerts works fine but trying to create prompts throws the above error. Is this a 1.2.0 only patch? Im testing using 1.1.0

**Comment by mgcrea** [comment]
Nop, that strange, it should work on any 1.x (regarding this https://github.com/aflx/pg_downloader_plugin_ios/issues/1)

I've taken `[arguments pop]` from the official docs (http://wiki.phonegap.com/w/page/36753496/How%20to%20Create%20a%20PhoneGap%20Plugin%20for%20iOS).

**Comment by max-mapper** [comment]
im upgrading to 1.2.0 now to see if that fixes it

**Comment by max-mapper** [comment]
Upgrading to PhoneGap 1.2.0 and migrating to a fresh project fixed the issue with Array.pop

**Comment by max-mapper** [comment]
@mgcrea also how does this compare to the existing Prompt plugin in your opinion?

**Comment by mgcrea** [comment]
@maxogden : its codebase is way simpler for the same task, it is developed accordingly to latest phonegap standards, it provides more options (placeholder, prompt message, textFieldType), and at last it adds a new unified api to alert/confirm & prompt. Did hesitate to fork prompt, but the codebase seemed over-complicated, & finally decided to start fresh.

**Comment by max-mapper** [comment]
@mgcrea fair enough. might be worth it to put those reasons in the readme so people dont get confused about which one to use (or contact the Prompt maintainer)

**Pull request merged**
