### PR TITLE
Updated WebIntent Android plugin to be PhoneGap 3.0.0 compatible

### PR DESCRIPTION
**Pull request by avivais**

### CODE REVIEW

**Comment by nickgrossman** [comment]
Thanks for doing this!  

I have two quick questions: 

1) it appears the documentation has a typo in it -- references to "CDV.WEBINTENT.WebIntent.EXTRA_TEXT" should actually be "CDV.WEBINTENT.EXTRA_TEXT", correct?

2) For some reason, I still can't get this plugin to correctly pick up an intent.  Here's the code for my app -- where I check for the current intent's EXTRA_TEXT, it always returns false even though it's definitely there (e.g, when responding to a SEND intent from a web browser).

Thanks!
Nick

**Comment by avivais** [comment]
1. Thanks for bringing that to my notice. Updated.
2. You haven't attached the code

**Comment by nickgrossman** [comment]
Weird, sorry about that.

As it happens, the problem was on my end -- I was in fact able to pick up the intent properly.

Thanks again for doing this, and I hope it makes it back into the official phonegap repo soon -- this was confusing for a while there.

**Comment by BraisGabin** [comment]
Works great!

**Comment by BraisGabin** [comment]
I just adapt the plugin to [The Command-line Interface](http://cordova.apache.org/docs/en/3.0.0/guide_cli_index.md.html): https://github.com/InQBarna/WebIntent

You can install the plugin using the command line now:

``` bash
cordova plugin add https://github.com/InQBarna/WebIntent.git
```

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Pull request closed without merging**
