### PR TITLE
MapKitView Plugin

### PR DESCRIPTION
**Pull request by MrBuzzy**
Switch to JSONKit, for compatibility with PhoneGap 1.2 (SBJson was
removed). Use ARC.

### CODE REVIEW

**Comment by MrBuzzy** [comment]
My first pull request, feedback appreciated.

**Comment by max-mapper** [comment]
@MrBuzzy nice and straightforward patch, thanks! the biggest problem with this repo right now is the various state of compatibility between all of the plugins and phonegap versions so I added a little comment about compatibility just to be extra clear.

**Comment by MrBuzzy** [comment]
@maxogden thanks! 
How can I relate this fix to the issue: https://github.com/phonegap/phonegap-plugins/issues/247
Or did that happen auto-magically?

**Comment by max-mapper** [comment]
@mrbuzzy to do it automagically you could have put 'fixes #247' in the commit message in your pull req

**Pull request merged**
