### PR TITLE
TestFlight:  Added the setDeviceIdentifier API

### PR DESCRIPTION
**Pull request by jschwartz73**
Hello,

I've modified the TestFlight plugin to include the setDeviceIdentifier API.

Sincerely,
Jeff Schwartz

### CODE REVIEW

**Comment by eyalfx** [comment]
For some reason it's not working out for me. I do get the correct uuid from device.uuid but on my testFlight dashboard users still show up as anonymous.
Can you give me an sample of how it should be used.
Here's what I'm doing.
Thanks,

```
    Tweets.testFlight.setDeviceIdentifier(
        function(){
            console.log("Success! " + Tweets.uuid);
        },

        function() {
            console.error("Failed!");
        },

        device.uuid
    );
```

**Comment by jschwartz73** [comment]
Eyal,

Are you getting the success message?

I'm seeing the same problem on the test flight side where all users are
anonymous… i believe it's a test flight problem.

Sincerely,
Jeff Schwartz

On Sun, Jun 10, 2012 at 5:58 PM, Eyal Erez <
reply@reply.github.com

**Comment by eyalfx** [comment]
Hi Jeff,
Yes, I am getting the success message.
I've also tried calling Tweets.testFlight.setDeviceIdentifier() after the takeoff() has return success to make sure it's initialized first, but same results.
I guess it is a testFlight issue.
Thanks though :)

**Comment by jschwartz73** [comment]
It did work when i first coded it a few weeks ago.

I'll look into it in a few days.  The plugin doesn't do anything other than
call TestFlight's api.

Sincerely,
Jeff Schwartz

On Mon, Jun 11, 2012 at 5:35 PM, Eyal Erez <
reply@reply.github.com

**Comment by christianseel** [comment]
According to http://docs.phonegap.com/en/2.0.0/cordova_device_device.md.html#device.uuid
device.uuid is not the same identifier that we add to testflight.

> iOS Quirk 
> 
> The uuid for iOS is not unique for a device, but is unique per application per install. This will change if you delete the app and re-install, and possibly also when you upgrade your iOS version, or even upgrade your app per version (as we've seen in iOS 5.1). Not a reliable value.

...this might be the answer why it's not working as expected?

**Comment by eyalfx** [comment]
Christian... that makes a lot of sense.
Did you get it to work in phone gap?
What did you use instead of device.uuid ?
Thanks

**Comment by randuhmm** [comment]
@christianseel  and @eyalfx

I was able to write up a workaround by adding in some code to expose the "UDID". My changes are in the CDVDevice.m and the Cordova JavaScript files. Also, I am using version 2.0.0 of Cordova.

~/Documents/CordovaLib/Classes/CDVDevice.m (Lines 62-76)

``` objective-c
- (NSDictionary*) deviceProperties
{
    UIDevice *device = [UIDevice currentDevice];
    NSMutableDictionary *devProps = [NSMutableDictionary dictionaryWithCapacity:6];
    [devProps setObject:[device model] forKey:@"platform"];
    [devProps setObject:[device systemVersion] forKey:@"version"];
    [devProps setObject:[device uniqueAppInstanceIdentifier] forKey:@"uuid"];
    [devProps setObject:[device name] forKey:@"name"];
    [devProps setObject:[[self class] cordovaVersion] forKey:@"cordova"];

    [devProps setObject:[device uniqueIdentifier] forKey:@"udid"];

    NSDictionary *devReturn = [NSDictionary dictionaryWithDictionary:devProps];
    return devReturn;
}
```

cordova-2.0.0.js (Lines 3987-4018)

``` javascript
/**
 * This represents the mobile device, and provides properties for inspecting the model, version, UUID of the
 * phone, etc.
 * @constructor
 */
function Device() {
    this.available = false;
    this.platform = null;
    this.version = null;
    this.name = null;
    this.uuid = null;
    this.udid = null;
    this.cordova = null;

    var me = this;

    channel.onCordovaReady.subscribeOnce(function() {
        me.getInfo(function(info) {
            me.available = true;
            me.platform = info.platform;
            me.version = info.version;
            me.name = info.name;
            me.uuid = info.uuid;
            me.udid = info.udid;
            me.cordova = info.cordova;
            channel.onCordovaInfoReady.fire();
        },function(e) {
            me.available = false;
            utils.alert("[ERROR] Error initializing Cordova: " + e);
        });
    });
}
```

With this code, you can now access the actual UDID with the property `device.udid`. By sending the UDID rather than the UAIID (Unique Application Instance IDentifier) TestFlight will be able to identify users.

**Comment by shazron** [comment]
Bad idea - Apple has deprecated this in iOS 5, and removed this in iOS 7 (try compiling it in Xcode 5) and apps using this will be rejected.

**Comment by jackocnr** [comment]
So what identifier should we use?

**Comment by shazron** [comment]
Create your own.

**Comment by jackocnr** [comment]
Thanks for your quick response. But as others have already said: sending anything except for the UDID (e.g. device.uuid) doesn't seem to work - sessions are coming up as anonymous. Or is there a way to link our TestFlight users to our own custom ID system?

**Comment by shazron** [comment]
Not sure how TestFlight's internals work - I don't think they have updated guidance on this.

If you are using my plugin, there is an API function to use Apple's recommended way to get a semi unique identifier:
https://github.com/shazron/TestFlightPlugin/blob/master/www/testflight.js#L123-L131

**Comment by jackocnr** [comment]
Yes I am using your plugin (it's great - thank you). I tried calling setDeviceIdentifierUUID instead of setDeviceIdentifier, but it didn't work (all activity in TestFlight dashboard is still Anonymous).

**Comment by shazron** [comment]
Yeah, TestFlight needs to solve this somehow. Also, if you have issues with the plugin its best to file them in the plugin repo itself, not here.

**Pull request merged**
