### PR TITLE
[Android] LocalNotifications Launch Activity on Acknowledge

### PR DESCRIPTION
**Pull request by ghost**
These small changes allow the local Notification to, when tapped, launch the app that created them. 

Please ignore iOS Plugin Additions (or review carefully; someone already made such changes, the merge may not quite work out...)

### CODE REVIEW

**Comment by macdonst** [comment]
Can you do a merge and re-submit your pull request?

**Comment by ghost** [comment]
:) I don't know how :)

## 

James Robert Perih
james.perih@nerdsonsite.com
Cell: 204.688.6211
Nerds On Site
www.nerdsonsite.com

Sent from my Windows Phone on the Telus Mobility Network

**Comment by matiasleidemer** [comment]
:+1:

**Comment by matiasleidemer** [comment]
I did all the changes in the files (the android ones), but I can't get it to work. The user taps the notification but nothing happens. Any tips?

**Comment by ghost** [comment]
Can we skype? JamesPerih
Will have to take a look, i may have missed describing a step.

Sent from Samsung tablet

"Matias H. Leidemer" notifications@github.com wrote:

I did all the changes in the files (the android ones), but I can't get it to work. The user taps the notification but nothing happens. Any tips?

**Comment by matiasleidemer** [comment]
The problem lies in the line 86:

``` java
final Intent notificationIntent = new Intent(context, YOURACTIVITY.class); 

//should be the notificationIntent, not a new Intent()
final PendingIntent contentIntent = PendingIntent.getActivity(context, 0, new Intent(), 0); 
```

You create a new intent, instead of using the one created above...

**Comment by ghost** [comment]
I'll try that with my code.

Sent from Samsung tablet

"Matias H. Leidemer" notifications@github.com wrote:

The problem lies in the line 86:

final Intent notificationIntent = new Intent(context, YOURACTIVITY.class);

//should be the notificationIntent
final PendingIntent contentIntent = PendingIntent.getActivity(context, 0, new Intent(), 0);

You create a new intent, instead of using the one created above...

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904
https://github.com/phonegap/phonegap-plugins/issues/889

**Pull request closed without merging**
