### PR TITLE
some iOS mapkit enhancements

### PR DESCRIPTION
**Pull request by max-mapper**
the mapkit plugin hasn't been touched since december (very sad) so I took a stab at including some stuff that was shared on the mailing list but never put into git and also cleaned up a few functions to make them more useful/modular. 

here's some examples of the new functionality:

max.couchone.com/test/401935f5806735e03a93d025b1047ba9/dynamic-map-loading.mov
max.couchone.com/test/401935f5806735e03a93d025b1047ba9/mapkit-hacks.mov

this is the first time i've written/hacked on objective-c so set your expectations to low :)

### CODE REVIEW

**Comment by shazron** [comment]
Unfortunately, your commits can't be merged automatically through Github. You'll need to resolve this first.

**Comment by max-mapper** [comment]
Alright I rebased on top of your master and also updated the demo page

**Comment by shazron** [comment]
Still the same problem. Don't worry, I'll do a manual merge tomorrow, and just cherry pick the relevant commits.
Although this change is not good: https://github.com/maxogden/phonegap-plugins/blob/91b7ad1d5f5bd36ba28464f7bc01c0a5a64f0513/iPhone/MapKitPlug/src/MapKit.h#L11-L13

With the 1.0.0rc1 being released tomorrow, PhoneGapCommand ceases to exist. Besides, PGPlugin already exists in 0.9.6 as well.

**Comment by shazron** [comment]
Ok, manually merged it in. Next time I won't be so generous ;)

**Comment by max-mapper** [comment]
Thanks! 

I guess I'm a bit confused... I rebased on top of HEAD from phonegap/master as of ~11PM last night and made sure everything was up to date. Why wasn't github able to manually merge? Also, is there a way for me to see when my pull requests are screwed up?

**Comment by shazron** [comment]
Dunno man :( I guess Github saw what I saw as well, there was a conflict in one line. Yeah the line was where the base had "self.webView" and you only had "webView" - can't find it at the moment...

**Comment by max-mapper** [comment]
ahh crazy! thanks for the help

**Pull request closed without merging**
