### PR TITLE
Update iOS/BarcodeScanner/README.md

### PR DESCRIPTION
**Pull request by jcrutch**
The plist key value needs to be com.cordova.barcodeScanner.

### CODE REVIEW

**Comment by shazron** [comment]
This is not correct. It should still be the old value. See: https://github.com/phonegap/phonegap-plugins/blob/master/iOS/BarcodeScanner/barcodescanner.js#L47

**Comment by jcrutch** [comment]
If you say so.  All I know is it would work for me until I changed the key.  It took me a while to find the solution on google.  I just thought I would save someone time.

**Comment by jcrutch** [comment]
would not :)

**Comment by shazron** [comment]
It is not a matter of my saying so, it is fact, right there in the javascript file. I'm interested in seeing your same file - perhaps it is different than the one in the repo.

**Comment by lobsterhc** [comment]
For the XIB Overlay PGbcsViewController needs to be updated to CDVbcsViewController (or really anywhere in the project that still references PG instead of CDV for barcode scanner -- at least for Cordova 2.2).. as for the plist key I just got it working yesterday on Cordova 2.2 with org.apache.cordova.barcodeScanner and CDVBarcodeScanner

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904

**Comment by devgeeks** [comment]
Not merging this as it seems to still be in debate? @shazron ?

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Pull request closed without merging**
