### PR TITLE
CDVSMSComposer update to 3.0.0

### PR DESCRIPTION
**Pull request by RandyMcMillan**
I tested for cdv 3.0.0
seems to work fine.
(:

### CODE REVIEW

**Comment by insight2learn** [comment]
Hi Randy, Cannot get this to work on Phonegap 3.0.0
I have followed your guide, but I get an error when running the sample html

[CDVCommandQueue executePending] [Line 116] FAILED pluginJSON = [
  "INVALID",
  "CDVSMSComposer",
  "showSMSComposer",
  [
    "recip1,recip2",
    "body"
  ]
]

I have the CDVSMS files appearing in the project fine.

I am also confused by your example html, as the calls seem to have typo's

```
            function init (recip1,recip2,body) {

                cordova.exec(null, null, "CDVSMSComposer", "showSMSComposer",["recip1,recip2","body"]);

            }

            function show () {

                cordova.exec(null, null, "CDVSMSComposer", "showSMSComposer",["recip1,recip2","body"]);

            }
```

**Comment by RandyMcMillan** [comment]
i'll review it.

**Comment by insight2learn** [comment]
Cool, thanks Randy, I was also looking for the plugin.xml so that I can add this plugin from the command line

**Comment by RandyMcMillan** [comment]
I haven't configd it for command line...
Been too busy with other stuff

Check out my templates...just look at my repos.  I have iOS and OSX
templates for Cordova

**Comment by insight2learn** [comment]
Hi Randy, sorry didn't mean to chase / offend.  I am just learning Cordova / Phonegap having been developing Java for a number of years (back end servers mainly)  I have been trying to find details on how to build new phonegap 3.0 plugins, and I would be happy to help your great work where I can.  Thanks ;-) you can DM me at @_markwiltshire

**Comment by RandyMcMillan** [comment]
No offense taken.

Check out:

https://github.com/RandyMcMillan/cdv-ios-plugin-templates

https://github.com/RandyMcMillan/cdv-osx-plugin-templates

I haven't bothered configuring these plugins for command line because the ones I maintain in my repos don't need it. Maybe I'll get to it at some point but it isn't a priority.

**Pull request closed without merging**
