### PR TITLE
[iOS] Allows ChildBrowser to open files in the assets folder

### PR DESCRIPTION
**Pull request by mcfedr**
such as pdfs or other html pages

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
hold on...

**Comment by shazron** [comment]
@RandyMcMillan holding on for 3 months now ;)

**Comment by Shereef** [comment]
i think it's safe to say you can let go for a while go to the bathroom and come back

**Comment by RandyMcMillan** [comment]
https://github.com/RandyMcMillan/PDFViewer

**Comment by mcfedr** [comment]
could i open a local html page or image file using pdfviewer?

Basically ChildBrowser is great, and it seems unnecessary to limit its functionality.

**Comment by RandyMcMillan** [comment]
It is meant for one purpose....to view PDFs that are included in your app. It is not meant to replace ChildBrowser nor does the documentation imply that. 

https://github.com/RandyMcMillan/PDFViewer#pdfviewer-for-cordova-ios

"Usage is exactly like ChildBrowser except you send a bundled pdf file name instead of an external url"

```
    cordova.exec('PDFViewerCommand.showPDF', 'CordovaBot.pdf');
```

CordovaBot.pdf is a local file.

It follows the same command pattern as ChildBrowser so its usage is familiar.

**Pull request closed without merging**
