### PR TITLE
Change calls from PhoneGap to Cordova in js

### PR DESCRIPTION
**Pull request by ckihneman**
I was a bit too hasty on submission, mixed up my versions. Here is the proper js file for GoogleAnalytics on iOS Cordova 1.5.0+.

### CODE REVIEW

**Comment by ckihneman** [comment]
Thanks for the help @shazron. Greatly appreciated. Hopefully this does it!

Worked for me on 1.5.0, can anyone confirm on 1.6.0?

**Comment by RandyMcMillan** [comment]
Lets close this and resubmit after its tested on 1.7. (If possible separate the /iOS and Android into separate commits. I personally prefer to increment the platforms separately. Just feels nicer.)

**Comment by ckihneman** [comment]
Well the issue at hand here is the version that is in master right now is not valid for Cordova at all, or even valid for older versions of phonegap - its broken. So if someone takes it and uses it as advertised right now in any Cordova, it will not work, and will throw javascript errors. It would be easy enough for someone to fix the javascript themselves, but it would be much better to just be commit now to make it work for people that need it now.

As for 1.7, i know nothing about it. Is backwards compatibility breaking once with this release?

**Comment by joelhegg** [comment]
I see this issue was closed. Is there a follow up issue? As @ckihneman says, what's in master right now doesn't work at all. I just tested his update on 1.7 and it works great.

**Comment by ckihneman** [comment]
Thanks for the confirmation @joelhegg. Good to know. Looks like this is ready to go.

**Pull request closed without merging**
