### PR TITLE
[Android] Analytics: Upgraded to support Version 2 of the Analytics SDK

### PR DESCRIPTION
**Pull request by CitizenOfRome**
### NOV, 14, 2012
- Upgraded to support Version 2 of the Google Analytics SDK
- Added the `stop` method
- Set it to use `EasyTracker`
- Removed Support for `setCustomVar` as the SDK no longer supports it

https://developers.google.com/analytics/devguides/collection/android/v2/migration

Should Close: #881, #483, #874, #758

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904

**Comment by CitizenOfRome** [comment]
@RandyMcMillan How does one use a label on a pull-request?
And why exactly did you close this, it's not just because of the label, is it?

**Comment by devgeeks** [comment]
Another one too Android-y for me feel comfortable merging...

@macdonst ?

**Comment by robdiciuccio** [comment]
Looks like the GA Android SDK 2.0 is still in beta. Perhaps this should be a new version (2.2) of the plugin, for those of us who still need setCustomVar?

**Comment by CitizenOfRome** [comment]
@robdiciuccio Yes, it is still in beta, but the issue is that Google is no longer accepting data from the older SDK version, so we are forced to upgrade.

https://developers.google.com/analytics/devguides/collection/android/v2/migration :

> With the release of the new Google Analytics Mobile App Analytics reports for Android , we've also introduced a new app profile type and a new set of app reports to designed specifically for analyzing your app usage data. **Keep in mind that new app profiles and reports will only accept data from version 2 or higher of the SDK**. See our Account Configuration Best Practices to learn more.

Are you still able to use GA with an older SDK?

**Comment by muszek** [comment]
I can confirm that with a newly created profile sathvikp's code works and the official repo's does not.

**Comment by robdiciuccio** [comment]
I am currently using GA SDK v1.5.1 successfully (with an existing profile) on Cordova 2.2.0. Why not make this a new version of the plugin, so both can coexist?

**Comment by CitizenOfRome** [comment]
**Changes**:
- Seperated the newer and older SDKs so that both can be used
- Maintaining the SDK 2.0 version at https://github.com/DoersGuild/Cordova-Android-Analytics
- Setup a readme file to this effect, as suggested by http://shazronatadobe.wordpress.com/2012/11/07/cordova-plugins-put-them-in-your-own-repo-2/

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Pull request closed without merging**
