### PR TITLE
Update Android Barcode Scanner to work with Phonegap 2.3

### PR DESCRIPTION
**Pull request by dvirus1023**
...ner/BarcodeScanner.java

### CODE REVIEW

**Comment by macdonst** [comment]
Please create a separate 2.2.0 directory for this type of work and you'll also need to fix the JavaScript.

**Comment by dvirus1023** [comment]
The code works without modifying any of the JavaScript. What needs to be updated?

Also, I am new to git, how would I create a separate directory for this?

**Comment by macdonst** [comment]
In your workspace just make a copy of the 2.0.0 directory to 2.2.0 directory. Make the change to the Java code in the 2.2.0 directory and create a new commit. Yes, the JS will work but I'd like to move to using the cordova.require way of doing things. If you are not comfortable with this I can do it once you submit the new 2.2.0 directory.

**Comment by dvirus1023** [comment]
Ok, Ill have to get the code on my machine and do this as I was just modifying in the browser. Once I have this complete ill resubmit. Ill take a look at the JS and see what needs to be done.

Thanks for the quick responses.

**Comment by dvirus1023** [comment]
As you can tell I am not very fluent in Git and GitHub.. It looks like it added my recent commit to the pull request. But I do not know how to remove the original edits to the 2.0.0 file.

I am not very comfortable with what needs to be done to implement the cordova.require into the JS. I will run with what I have until you are able to update.

Thanks for the help and please let me know if something did not commit correctly.

**Comment by macdonst** [comment]
You are going to need to create another commit to roll back your changes to BarcodeScanner.java in the 2.0.0 directory. Then I can merge it.

**Comment by dvirus1023** [comment]
Committed.

**Comment by fboulegue** [comment]
so here is a iOS Sample for C2.3 RandyMcMillan was so nice to add it https://github.com/phonegap/phonegap-plugins/pull/991

**Pull request merged**
