### PR TITLE
Needed to mimic Safari's "Open in iBooks" or "Open in Pages" functionality in ChildBrowser

### PR DESCRIPTION
**Pull request by ebzlo**
Added an open in external application link for when linking to doc files, pdfs, or any file that loads into ChildBrowser and could potentially be opened with an external application.

### CODE REVIEW

**Comment by ebzlo** [comment]
I made a change to the closeBrowser method, because it was failing on iOS5.

**Comment by shazron** [comment]
This pull request cannot be automerged anymore. Please rebase and send a new pull request

**Comment by RandyMcMillan** [comment]
Im going to take closer look at this now that ChildBrowser is working in Cordova.

**Comment by RandyMcMillan** [comment]
Im going to get to this.

**Pull request closed without merging**
