### PR TITLE
Local Notifications for Android

### PR DESCRIPTION
**Pull request by dvtoever**
Phonegap plugin for Android that allows an application to schedule (repeating) notifications

### CODE REVIEW

**Comment by macdonst** [comment]
@dvtoever this is awesome. I'm working on a sample app right now that needs exactly this functionality. This is going to save me a ton of work. Cheers!

**Comment by dvtoever** [comment]
Hey Md,

Glad my plugin is already useful :-)

Thanks for accepting the pull request.

Daniel

Verstuurd vanaf mijn iPhone

Op 8 feb. 2012 om 16:36 heeft macdonst
reply@reply.github.com
het volgende geschreven:

**Comment by josher19** [comment]
Any chance of porting the LocalNotification plugin to PhoneGap for Palm WebOS?

**Comment by dvtoever** [comment]
Hi Josher,

I have no experience with WebOS, but you could give it a try. On every
operating system it is a new puzzle to find if there are existing services
available in the OS that can be mapped to the notification interface:
- addAlarm
- cancelAlarm
- cancelAllAlarms

Good luck!

2012/5/4 josher19 <
reply@reply.github.com

**Comment by demophoon88** [comment]
Hi. Sorry this might be a dumb question. I dont have adept knowledge in Java(more of a php-css-html-jquery person) and I wanna ask about this line from the instructions.
1. Fix the import in AlarmReceiver.java around line 67 where R.drawable.ic_launcher is referenced so it matches an icon in your project

Thanks

**Comment by josher19** [comment]
I think that refers to this line of AlarmReceiver.java :

```
final Notification notification = new
```

Notification(R.drawable.ic_launcher, tickerText,
System.currentTimeMillis());

which assumes your Project Icon is named ic_launcher.

If you use Eclipse, you can give your project a new Icon Set by doing:

File | New | Other
   Android
      Android Icon Set

On Sat, May 19, 2012 at 4:56 PM, demophoon88
reply@reply.github.com
wrote:

**Comment by dvtoever** [comment]
You're right. It allows you to change the icon in the notification pane.

Verstuurd vanaf mijn iPhone

Op 21 mei 2012 om 08:42 heeft josher19
reply@reply.github.com
het volgende geschreven:

**Comment by demophoon88** [comment]
Hi. Thanks. Sorry for the late response. Just thought I'd share how I managed to fix.

On AlarmReceiver.java I added on top :

import com.phonegap.adhdapp.R;

and on LocalNotification.java(it was having errors as well) I followed this post:

http://stackoverflow.com/questions/10218745/trying-to-get-the-android-localnotification-plugins-for-phonegap-to-work-in-cord

Problem is im not sure how to test this. I can't see any notifcation(popup or status bar) and I've already followed the sample javascript provided. 

I'm using cordova 1.7 and Android ICS 4.0.3 btw

**Comment by anollipian** [comment]
I need to know how to change this function to work with cordova2.2  ?

```
    public PluginResult execute(String action, JSONArray optionsArr, String callBackId) {
alarm = new AlarmHelper(this.ctx);
Log.d(PLUGIN_NAME, "Plugin execute called with action: " + action);

PluginResult result = null;

final AlarmOptions alarmOptions = new AlarmOptions();
alarmOptions.parseOptions(optionsArr);

/*
 * Determine which action of the plugin needs to be invoked
 */
String alarmId = alarmOptions.getNotificationId();
if (action.equalsIgnoreCase("add")) {
    final boolean daily = alarmOptions.isRepeatDaily();
    final String title = alarmOptions.getAlarmTitle();
    final String subTitle = alarmOptions.getAlarmSubTitle();
    final String ticker = alarmOptions.getAlarmTicker();

    persistAlarm(alarmId, optionsArr);
    return this.add(daily, title, subTitle, ticker, alarmId, alarmOptions.getCal());
} else if (action.equalsIgnoreCase("cancel")) {
    unpersistAlarm(alarmId);
    return this.cancelNotification(alarmId);
} else if (action.equalsIgnoreCase("cancelall")) {
    unpersistAlarmAll();
    return this.cancelAllNotifications();
}

return result;
}
```

**Comment by conrad10781** [comment]
anollipian: Unfortunately ( at least on 2.0.0 ), there are several changes you'll need to make for this to work.

To answer your first question, replace this.ctx with this.cordova.getContext() in new AlarmHelper(). What you'll first find is that this.cordova.getContext() is deprecated.

What you'll find after that is that the LocalNotification.js file is going to need to be modified quite a bit to conform to the 2.x+ style for plugins.

After that, you'll finally find that the Javascript instantiation of the plugin is different, and you'll have slightly different syntax needed in your HTML/JS files.

I've made all of these changes already. I'd be happy to work with macdonst to figure out a way to possibly have two versions of the plug ( < 2.x and > 2.x ) available in here so others could benefit from it.

**Comment by kokmok** [comment]
Hi conrad10781. It could be great if the changes you made were hosted somewhere. So people could benefit from it. :)

**Comment by conrad10781** [comment]
kokmok , anollipian, et al: I've created a repository at https://github.com/conrad10781/phonegap-plugins/tree/master/Android/LocalNotification . This version has been tested on 2.0, 2.1, and 2.2 versions. I tried to keep the structure and instructions as close as I could to the original to ensure that any upgrade attempts would go as smoothly as possible.

**Comment by kokmok** [comment]
Thank you, very much ! :)

**Pull request merged**
