### PR TITLE
Fixing the prompt ios plugin for ios 5

### PR DESCRIPTION
**Pull request by peutetre**

### CODE REVIEW

**Comment by brianantonelli** [comment]
On iOS 4.3+ you should be able to just set the opaque property to NO and not have to mess with the background color.

`[theTextField setOpaque:NO];`

**Comment by peutetre** [comment]
ok thanks for the comment, I will fix it and append it to this pull request ;-)

**Comment by max-mapper** [comment]
@peutetre I just tested this pull req and it works well. Were you still going to append more commits to it before I merge it in?

**Comment by peutetre** [comment]
Sorry for the merge noise! 

Thanks @brianantonelli for the tip.

**Comment by max-mapper** [comment]
@peutetre thanks!

**Pull request merged**
