### PR TITLE
update iOS barcodescanner to support PhoneGap 2.0

### PR DESCRIPTION
**Pull request by tiratatp**
- update barcodescanner.js to support PhoneGap 2.0
- update zxing from 1.7 to 2.0

### CODE REVIEW

**Comment by pmuellr** [comment]
cool.  Did you run the "test suite" to make sure it can scan all the barcodes it could scan before?  Did any new formats get added?  (didn't appear to, given a quick scan of the code)

**Comment by jaroslavas** [comment]
Tried that and its working!
Tried codes: CODE_128 and QR_CODE, both are working on iphone 4.

Thank you a lot! :)

**Comment by guillaumebadin** [comment]
I tried it works very well. Congratulations to @nuttyknot

**Comment by pmuellr** [comment]
Sorry for the delay, since reports are positive, I was going to merge this pull request.  But apparently I've lost the ability to do that.  hmmmm

**Comment by tiratatp** [comment]
Do you need me to do anything?
This is my first pull request so
Please do help me on this.

Tiratat Patana-anake
On Aug 2, 2012 7:10 PM, "Patrick Mueller" <
reply@reply.github.com>
wrote:

**Pull request merged**
