### PR TITLE
Add android PayPal plugin

### PR DESCRIPTION
**Pull request by paulb777**
I can't figure out how to make a pull request with only my changes. Do I need to make a new fork from phonegap/phonegap-plugins? Or can the merger also accept the other changes from purplecabbage/phonegap-plugins?

### CODE REVIEW

**Comment by shazron** [comment]
Hi Paul, hmm don't know for sure. Are your 4 commits above the relevant changes? If so, i can cherry-pick it from you.

**Comment by shazron** [comment]
The other way would be to:
1. Fork phonegap/phonegap-plugins
2. create a branch for the commits you want to pull
3. cherry-pick the 4 commits from purplecabbage repo (after adding it as a remote)
4. do a pull-request from the branch in 2.

That's the way I was going to do it anyway.

**Comment by paulb777** [comment]
OK, I'll do that tomorrow if I don't hear anything else.

Thanks,
Paul

**Comment by paulb777** [comment]
Yes the bottom five are my changes.

**Comment by shazron** [comment]
Merged from pull request: https://github.com/phonegap/phonegap-plugins/pull/34

**Pull request closed without merging**
