### PR TITLE
Updated applicationPreferences/open In plugin for iOS to include Cordova 3.0 support

### PR DESCRIPTION
**Pull request by njtman**

### CODE REVIEW

**Comment by njtman** [comment]
Modified the outdated applicationPreferences plugin.  Updated this plugin's signature to the new Phonegap plugin signature that was introduced in 2.1.0, because the old plugin signature which this plugin previously used is no longer supported in Phonegap/Cordova 3.0.0.  This also required a change to the javascript plugin file, but there are no other changes that are required by the end user, just drop in the files and all will work.

**Comment by sp1985** [comment]
Great work.
I just installed Cordova 3.0.0 on my Mac using the CLI. How do I install this plugin? Using CLI?
Thnaks in advance.

**Comment by njtman** [comment]
It doesn't support plugman yet, but at the very least it will work with Cordova 3.0.  Install it like you would any other plugin.  You can follow the directions on the readme page of the plugin.
https://github.com/phonegap/phonegap-plugins/blob/master/iOS/ApplicationPreferences/README.md
As long as you use the files referenced in my repo, it will work with cordova 3.0.

**Comment by sp1985** [comment]
Thanks.

I have added the Settings.bundle.
I have copied the .h, .m and .js files.

In the debugger console, I can see that the object
"window.plugins.applicationPreferences" exists.
However, I do not see an alert, when I execute:

window.plugins.applicationPreferences.get('name_preference',
function(result) {
 alert("We got a setting: " + result);
}, function(error) {
alert("Failed to retrieve a setting: " + error);
 }
);

I would expect an alert even if the call fails.

In the readme file:
https://github.com/phonegap/phonegap-plugins/blob/master/iOS/ApplicationPreferences/README.md

I cannot complete the "Registering the plugin", since I cannot file
Cordova.plist.
Is this the reason for my problem?

I think that config.xml is used instead. How does you config.xml file look?

Thanks in advance.

**Comment by sp1985** [comment]
Now I have added the plugin as a feature in config.xml. I get this error:

2013-09-10 20:09:14.666 HelloWorld[28501:c07] Multi-tasking -> Device: YES, App: YES
2013-09-10 20:09:14.768 HelloWorld[28501:c07] Resetting plugins due to page load.
2013-09-10 20:09:14.960 HelloWorld[28501:c07] Finished load of: file:///Users/embryo/Library/Application%20Support/iPhone%20Simulator/6.1/Applications/3846ACB8-370D-4470-A75C-33398D0AE14B/HelloWorld.app/www/index.html
2013-09-10 20:09:14.997 HelloWorld[28501:c07] ERROR: Method 'getSetting:' not defined in Plugin 'applicationPreferences'
2013-09-10 20:09:14.998 HelloWorld[28501:c07] -[CDVCommandQueue executePending] [Line 116] FAILED pluginJSON = [
  "applicationPreferences1209187169",
  "applicationPreferences",
  "getSetting",
  [
    {
      "key" : "name_preference"
    }
  ]
]

**Comment by njtman** [comment]
In config.xml make sure you include

`<feature name="applicationPreferences">
          <param name="ios-package" value="applicationPreferences" />
</feature>`

The error you are receiving looks similar to the error I was getting while using the old plugin files with cordova 3.0, hence the need for me to upgrade them.

If the method signatures in your applicationPreferences.h file don't look like the ones seen below, you are using the old files.  Make sure to use the files from my repo and not the files from the master repo.
-   (void) getSetting:(CDVInvokedUrlCommand*)command;
-   (void) setSetting:(CDVInvokedUrlCommand*)command;
-   (NSString_) getSettingFromBundle:(NSString_)settingName;

Direct links to the files I updated are here

https://github.com/njtman/phonegap-plugins/blob/91559d915d2ebe4a05cca8f6848f2ad7e139af7c/iOS/ApplicationPreferences/applicationPreferences.h

https://github.com/njtman/phonegap-plugins/blob/10ab358956d1a57bc51411d67f10daefa3cb7b5a/iOS/ApplicationPreferences/applicationPreferences.m

https://github.com/njtman/phonegap-plugins/blob/801dbad6979f5ffd26e622a0b21749cfc89d7262/iOS/ApplicationPreferences/applicationPreferences.js

Download these and place them in the project and see if it works.  If this doesn't fix the problem, there could be a problem with your settings bundle.

**Comment by sp1985** [comment]
Excellent. It works.
Thanks.

Med venlig hilsen
Søren

---

Søren Porsgaard
sp@form-farve.dk
Tlf.: (+45) 42 41 42 14

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Pull request closed without merging**
