### PR TITLE
minor change to support iOS 5

### PR DESCRIPTION
**Pull request by RandyMcMillan**
minor change to support iOS 5

### CODE REVIEW

**Comment by shazron** [comment]
Why require users to comment/uncomment when you can do it at runtime? The code I put up at #74 is the more effective solution by checking for capabilities at runtime. 

Also, what is "presentingViewController"? I don't think this will compile anyway.

**Comment by RandyMcMillan** [comment]
presentingViewController is replacing parentViewController in the view hierarchy.

**Comment by shazron** [comment]
Ok now I understand, but this still won't compile under iOS 4, and will crash. You'll need to do the runtime checks of respondsToSelector etc to check for the presence of presentingViewController, and if it is present, use that. PHONEGAP_FRAMEWORK is not the way to do it, it has nothing to do with the iOS version used. You'll need to detect for presence of the member items. We have a lot of these checks in PhoneGap already, so iOS 3 / 4 can be inter-operable without crashing. Use respondsToSelector.

<pre>
if ([self respondsToSelector:@selector(presentingViewController)]) {
} else {
}

**Comment by purplecabbage** [comment]
cannot automatically merge, closing.  Is this still an issue?

**Pull request closed without merging**
