### PR TITLE
[Android] Childbrowser loading indicator

### PR DESCRIPTION
**Pull request by CitizenOfRome**
### Jan, 8, 2013
- Set an indicator (footer) to be shown while a page in the child-browser is loading
- This is almost entirely based on pull #677

Affects: #677, #571

TODO: Allow the user to specify if this should be shown

### CODE REVIEW

**Comment by macdonst** [comment]
Once you have the ability to specify whether the loading image should be show or not resubmit the pull request.

**Comment by CitizenOfRome** [comment]
@macdonst It's done; please check #965

**Comment by macdonst** [comment]
Probably get to it tonight. On another project right now.

**Comment by CitizenOfRome** [comment]
Np, take your own time

**Pull request closed without merging**
