### PR TITLE
New Print Plugin

### PR DESCRIPTION
**Pull request by itip**
Hi,

I have created a new PhoneGap plugin which enables iOS devices to print to AirPrint-compatible printers. I would very much like for this plugin to be part of the main PhoneGap plugins (if you think it is good enough).

iPhone/PrintPlugin.

Thanks,

Ian

### CODE REVIEW

**Comment by salhidiq** [comment]
Hello,
Im very much interested in the plugin, how can we get it and try it out?

Cheers,
S.

**Comment by itip** [comment]
Hi,

There are two ways to download the plugin:

1) The easiest way is to go to
https://github.com/phonegap/phonegap-pluginsand download the plugins
in a ZIP file (this will include all of the
plugins so you'll need to extract the ZIP file and navigate to
iPhone/PrintPlugin).

2) If you're familiar with Git then you can clone the repository. This has
the added advantage that you can easily download updates to the plugins by
doing a 'git pull'. With the first option you'd need to download the ZIP
file every time the code changes.

I hope that helps. Let me know if you have any issues.

Ian

On 30 December 2011 19:47, salhidiq <
reply@reply.github.com

**Comment by salhidiq** [comment]
Hello itip,
Thanks for your feedback.

I have a problem, I compile and I get your HTML page with the button "Print the HTML before".
When I click it, nothing happens.

Am I missing anything?

Thanks,
S.

**Comment by itip** [comment]
Hi,

Is anything displayed in the PhoneGap log files? (I suspect there will
be a JavaScript error of some sort).

Would you mind letting me know which version of PhoneGap you're using?
I will use that to verify whether the plugin works with that version.

Thanks,

Ian

On 1 Jan 2012, at 20:17, salhidiq
reply@reply.github.com
wrote:

**Comment by salhidiq** [comment]
Hello Ian,

In the debugger, I get:
[WARN] warning: no rule to process file '$(PROJECT_DIR)/www/PrintPlugin.js' of type sourcecode.javascript for architecture armv7
I put the js in the www folder and declared it in the pugins section.

Im using Xcode latest version.

Thanks,
S.

**Comment by itip** [comment]
Hi,

Ok, thanks. I think I'll just need to update some of the compiler
settings. Leave it with me... :)

Ian

On 1 Jan 2012, at 20:44, salhidiq
reply@reply.github.com
wrote:

**Comment by salhidiq** [comment]
Hey Ian,

I look forward to your updates, need to get the Print feature up and running by tomorrow :)
I have an HTML that is loaded with values from the local database and need to print it so very excited by your feedback.

As much details as possible for guidance and Ill be appreciative as this is a topic hard to configure and get running.

Cheers,
S.

**Comment by itip** [comment]
Hi,

I haven't actually tried running the code yet but I've done a search
on Google and it looks like other people have had the same issue. From
what I can tell, it doesn't look the issue is with the plugin
(although I'll double check tomorrow).

I would recommend looking at the following.

http://stackoverflow.com/questions/4430786/warning-no-rule-to-process-javascript-for-architecture-armv7

http://stackoverflow.com/questions/7201300/when-i-am-trying-to-run-the-javascript-i-am-finding-some-warnings-how-to-overcom

Ian

On 2 Jan 2012, at 00:12, salhidiq
reply@reply.github.com
wrote:

**Comment by salhidiq** [comment]
Hey Ian,
I managed to get rid of the error in the log, but still I click on the Print button in the index.html file you provided and it does nothing.
Any ideas?
Have you tried the print plugin successfully?

Thanks,
S.

**Comment by itip** [comment]
Hi,

It looks like someone else has resolved this issue but the 'pull request'
hasn't yet been added brought into the main project (which is why you
wouldn't have seen it).

If you follow these instructions then it should work:

If you have issues with the app crashing with EXC_BAD_ACCESS on iOS
Simulator you may have a weak linking issue. With your project highlighted
in the left column in XCode go to Targets > Your Project > Build Settings >
Linking > Other Linker Flags and replace -weak_library with -weak-lSystem For
more information see:
http://stackoverflow.com/questions/6738858/use-of-blocks-crashes-app-in-iphone-simulator-4-3-xcode-4-2-and-4-0-2

Ian

On 2 January 2012 10:38, salhidiq <
reply@reply.github.com

**Comment by salhidiq** [comment]
Hi,
I dont have any entry under 'other Linker Flags', I have debug and release, thats it!
I tried before running in simulator 4.3, 5.0 and on an iPad2, the Print button when clicked simply doesnt do anything.

Any ideas?

S.

**Comment by itip** [comment]
Hi,

Try adding the setting anyway. Also, it might be worthwhile you creating a
new project to find the default settings.

Ian

On 2 January 2012 12:48, salhidiq <
reply@reply.github.com

**Pull request merged**
