### PR TITLE
Update Android BarcodeScanner ant build.xml to work with new Android SDK...

### PR DESCRIPTION
**Pull request by jwark**
... (take 2)

Update Android BarcodeScanner ant build file to work with newer Android SDK. 
I was not sure what to do about all of the *.properties file references, since I was not using them (hopefully I haven't removed any that people are using).

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904

**Comment by devgeeks** [comment]
This one is too big a change and too Android-y for me to be comfortable merging... 

@macdonst - can you have a look at this?

Or @jwark - perhaps contact me via twitter or email or whatever and talk me through it... (this is Tommy from MelbJS by the way).

**Comment by jwark** [comment]
I'm happy to answer any questions @devgeeks or @macdonst - essentially I changed the ant build.xml file to work with the newer Android SDK.  The existing build.xml fails since there are Java libraries (JAR's) which seem to no longer be included in the SDK.
What more would you like to know?

**Comment by devgeeks** [comment]
It just also seems like there are a lot of removed targets as well, up to and including the "help" target.

**Comment by jwark** [comment]
It is possible that I have removed more than necessary, however for compilation and packaging my application, this build.xml works fine.  Maybe someone with more PhoneGap Android Plugin experience can have a look (this is really my first time)?

**Comment by ARolek** [comment]
This is much needed.  My build tools can't compile with the current build.xml.  I would suggest though that you move the sdk requirement to local.properties instead of project.properties, as local.properties is suppose to be for the local environment and not checked into version control.

**Comment by devgeeks** [comment]
@macdonst has been otherwise engaged lately, but I will ping him again on this and see if he has time to look at it.

**Comment by ARolek** [comment]
ok.  fwiw, I was able to use the proposed build.xml file in my project using the new Android SDK.

**Comment by macdonst** [comment]
Hey sorry, I've been sick. Why do we need to change the build script? In order for the BarcodeScanner to work properly we're including it in as a library project which bypasses the ant build.xml anyway.

**Comment by ARolek** [comment]
Sorry for the slow response on my side. I took some time off over the holidays.

I was having problems building with the current build.xml file, and I was including the project as a library. With the suggested build file I was able to build my project no problem. I'm not an Android expert, so I might be missing something in my flow. 

I did not use Eclipse to include the library, but instead used the command line.  If it would be helpful, I can write down the command line steps I used for reference.

**Comment by macdonst** [comment]
@ARolek yeah, if you could write up the steps for the command line that'd be great and we could put a second build.xml called something line build.cmdline.xml for folks who want to do it that way.

**Comment by ARolek** [comment]
@macdonst no problem. Here are the instructions

The following commands are for Linux \ Unix OS and assume you have the android sdk installed, and it is available from your command line by calling: `android`
- the basic command to include a library project is as follows:

```
android update project --target <target_ID> --path path/to/your/project --library path/to/library_project
```

_--target_ is the android id associated with the API you are targeting. You can get a list of the ids by running `android list`
_--path_ is the path to your project. if you run the command from inside your project directory you can simply use a dot (.)
_--library_ **relative** path to your library project. I repeat, this must be a **relative** path.
- an example of the command run from the root of a project

```
android update project --target 9 --path . --library ../../libs/phonegap-plugins/Android/BarcodeScanner/LibraryProject
```

If all goes well, your local.properties file should have added a line similar to:

```
android.library.reference.1=../../Lib/phonegap-plugins/Android/BarcodeScanner/LibraryProject
```

You should now be able to build your project running:

```
ant release
```

Let me know if you have any problems, or questions.

[Additional information](http://developer.android.com/tools/projects/projects-cmdline.html#ReferencingLibraryProject)

**Comment by shazron** [comment]
This repo has been deprecated and will not be actively maintained - no pull requests nor any other issues will be worked on. The previous source currently exists in the DEPRECATED branch, and may be removed at a future date.
Migration path, see: https://github.com/phonegap/phonegap-plugins/blob/master/README.md

**Pull request closed without merging**
