### PR TITLE
Updated MapKit plugin (iOS) to Cordova 2.8 / 2.9

### PR DESCRIPTION
**Pull request by ronaldpk**
Updated the old MapKit plugin for iOS to work with Cordova 2.8 and 2.9. Also added an example, using Cordova 2.9.0.

### CODE REVIEW

**Comment by sromalewski** [comment]
This is a great update, thanks for putting it together.

Question: in my app the user has the option of zooming in on a map to a radius around their location, and the radius is dynamic based on a preference they can set.  In the current version of my app (using Cordova 2.3 and the old MapKit plugin), I can set the map diameter using the "_options" variable in the showMap method.  But in your plugin, though I can change the map diameter value but it doesn't seem to have an effect on the map itself.  It still zooms in to the old value.

Thoughts?  I'd be glad to share code snippets if that's helpful.

**Comment by ronaldpk** [comment]
Works fine in the example app... I basically show the map like this (example without callbacks):

```
setMapData({diameter: 500});
showMap();
// zooms in pretty deep
hideMap();
setMapData({diameter: 5000});
showMap();
// gives a broader view
```

**Comment by sromalewski** [comment]
Thanks, though now I'm a bit confused.  I was using the code from https://github.com/RonaldPK/MapKit .  But now I see that there's also this code: https://github.com/RonaldPK/phonegap-plugins/tree/master/iOS/MapKit which is different, and perhaps what you're referencing above?

**Comment by ronaldpk** [comment]
https://github.com/RonaldPK/MapKit offers a fix for https://github.com/imhotep/MapKit , which is a plugin for iOS and Android. It is best to open a new issue at https://github.com/imhotep/MapKit for the diameter issue.

The other one updates the old MapKit plugin in this plugin repository, here at /phonegap/phonegap-plugins.

**Pull request closed without merging**
