### PR TITLE
[Android] Google Play In App Billing plugin

### PR DESCRIPTION
**Pull request by poiuytrez**
New Android plugin. 
Compatible with Cordova 2.0

### CODE REVIEW

**Comment by poiuytrez** [comment]
Hey, could someone review my plugin? 
Thanks!

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904
https://github.com/phonegap/phonegap-plugins/issues/889

**Comment by devgeeks** [comment]
@poiuytrez  - Consider moving this to your own repo instead: 

http://shazronatadobe.wordpress.com/2012/11/07/cordova-plugins-put-them-in-your-own-repo-2/

**Comment by pudiganapathi** [comment]
@poiuytrez nice plugin .pefectly work and restore .
can you provide plugin for InAppBillingV3?????

**Comment by poiuytrez** [comment]
Please use only one question mark and post messages related to the plugin on the plugin issue tracker: https://github.com/poiuytrez/AndroidInAppBilling/issues?state=open

**Pull request merged**
