### PR TITLE
Update to the LocalNotification Plugin

### PR DESCRIPTION
**Pull request by DrewDahlman**
I have made some updates to the LocalNotification plugin that now allow for callbacks and sound, also added a hack / fix for the occasional app crash when launching from a notification.

I've also added the didReceiveLocalNotification method to the AppDelegate.m file, as well as commenting out portions of the didFinishLaunchingWithOptions since that's seems to cause the random crashing, I've also documented that!

I have documented the full changes here
﻿http://www.drewdahlman.com/meusLabs/?p=117

Cheers!

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
Please recreate in Cordova 1.5 and if it still exists resubmit.

Check out the "Cordova Plugin Upgrade Guide.pdf" currently bundled with the Cordova 1.5 download. http://phonegap.com/download-thankyou

**Comment by DrewDahlman** [comment]
yeah seems like the PDF isn't in that bundle... also the documentation seems old...

**Comment by DrewDahlman** [comment]
nevermind sorry. found it.

**Comment by RandyMcMillan** [comment]
Be sure to submit the revision under the new iOS folder. I think it is prudent to preserve the "PhoneGap" plugins and migrate plugins that support CDV to /iOS. There are dev entities that aren't necessarily updating to new releases. This is the perfect and only time to migrate.

**Pull request closed without merging**
