### PR TITLE
[iOS] Update EncodeAudio for Cordova 2.1.0

### PR DESCRIPTION
**Pull request by keenan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
https://github.com/phonegap/phonegap-plugins/issues/904
https://github.com/phonegap/phonegap-plugins/issues/889

**Comment by devgeeks** [comment]
@keenan - consider hosting this in your own repo if you are interested in maintaining this fork...

http://shazronatadobe.wordpress.com/2012/11/07/cordova-plugins-put-them-in-your-own-repo-2/

**Comment by keenan** [comment]
I refined and posted it here with a demo project. Can you link to it from the main phonegap plugin repo?
https://github.com/keenan/cordova-phonegap-audio-encode

**Comment by devgeeks** [comment]
Can you just do a pull req that deletes all the files except for the README and put the new location in the README?

**Comment by keenan** [comment]
Done

**Comment by devgeeks** [comment]
...and done! 

Thanks.

**Pull request merged**
