### PR TITLE
Geofencing Added

### PR DESCRIPTION
**Pull request by radshag**
This is a new Plugin to Support Geofencing in iOS PhoneGap Apps.

### CODE REVIEW

**Comment by max-mapper** [comment]
WHOA COOL! i'll test this out and if it works merge it in!

**Comment by max-mapper** [comment]
@radshag @dovgoldberg couple of questions:
- the radius seems to be hardcoded at 10 meters, do you think this should be configurable?
- the readme is missing an example of calling `addRegion`  with some actual arguments (the js has some documentation but it is still a little confusing)

**Comment by dovgoldberg** [comment]
Max

I agree that radius should be configurable. I have used this plugin in a
project of mine. I will add clear documentation to the reader and a link to
my repo with the working sample.

Thanks

Dov

**Comment by radshag** [comment]
Max,

I would like to have my plugin already registered in the didFinishLaunchingWithOptions.

This way when the device sends a region notification my plugin is already in memory.

How can I do this?

I have something like this:  
    // DGGeofencing Plugin is Registered here.  This way it can process crossovers in the background
    DGGeofencing *geoFencePlugin = [self.viewController getCommandInstance:@"DGGeofencing"];

But then I find that the callback from Objective C to Javascript doesn't work....

Thanks,

Dov

**Comment by max-mapper** [comment]
Hmm maybe @shazron knows

**Comment by radshag** [comment]
Ok Max,

I have added a full readme to explain everything.  The plugin has been updated.

I also include a sample project in my repository and a link can be found in the readme.md file.

Please let me know if there are any other issues.  I hope things go smoothly now.

Thanks,

Dov

**Comment by max-mapper** [comment]
awesome work, Dov!

**Comment by max-mapper** [comment]
I have a follow up question -- would it make sense to put functionality for the significant-change location service in this plugin? I was thinking of adding it in since you have a nice base layer for accessing CLLocation from JS

**Comment by devgeeks** [comment]
Lots of people are interested in "significant change" functionality. If this is a good fit, there would be a great deal of interest.

**Comment by dovgoldberg** [comment]
Can you provide the name of the function you would like to put in. I have a pretty good idea of what you want. I think it would be great to put it in and would have no issues with doing it.

**Comment by max-mapper** [comment]
Heya Dov -

The API is startMonitoringSignificantLocationChanges as described here:
http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html

I could imagine an api where you tell your app to start monitoring
significant changes and then it calls a callback every
time locationManager:didUpdateLocations: fires

**Pull request merged**
